#ifndef __idtbl_h__
#define __idtbl_h__

#define null_index 0
#define identifier_0 1
#define indx_constant_0 2
#define indx_constant_1 3
#define indx_constant_2 4
#define indx_integer_constant_0 5
#define indx_integer_constant_1 6
#define indx_integer_constant_2 7
#define indx_emumeration_constant_0 8
#define indx_character_constant_0 9
#define indx_string_literal_0 10
#define indx_primary_expression_0 11
#define indx_primary_expression_1 12
#define indx_primary_expression_2 13
#define indx_primary_expression_3 14
#define indx_postfix_expression_0 15
#define indx_postfix_expression_1 16
#define indx_postfix_expression_2 17
#define indx_postfix_expression_3 18
#define indx_postfix_expression_4 19
#define indx_postfix_expression_5 20
#define indx_postfix_expression_6 21
#define indx_postfix_expression_7 22
#define indx_postfix_expression_8 23
#define indx_postfix_expression_9 24
#define indx_argument_expression_list_0 25
#define indx_argument_expression_list_1 26
#define indx_unary_expression_0 27
#define indx_unary_expression_1 28
#define indx_unary_expression_2 29
#define indx_unary_expression_3 30
#define indx_unary_expression_4 31
#define indx_unary_expression_5 32
#define indx_unary_operator_0 33
#define indx_unary_operator_1 34
#define indx_unary_operator_2 35
#define indx_unary_operator_3 36
#define indx_unary_operator_4 37
#define indx_unary_operator_5 38
#define indx_cast_expression_0 39
#define indx_cast_expression_1 40
#define indx_multipricative_expression_0 41
#define indx_multipricative_expression_1 42
#define indx_multipricative_expression_2 43
#define indx_multipricative_expression_3 44
#define indx_additive_expression_0 45
#define indx_additive_expression_1 46
#define indx_additive_expression_2 47
#define indx_shift_expression_0 48
#define indx_shift_expression_1 49
#define indx_shift_expression_2 50
#define indx_relational_expression_0 51
#define indx_relational_expression_1 52
#define indx_relational_expression_2 53
#define indx_relational_expression_3 54
#define indx_relational_expression_4 55
#define indx_equality_expression_0 56
#define indx_equality_expression_1 57
#define indx_equality_expression_2 58
#define indx_AND_expression_0 59
#define indx_AND_expression_1 60
#define indx_exclusive_OR_expression_0 61
#define indx_exclusive_OR_expression_1 62
#define indx_inclusive_OR_expression_0 63
#define indx_inclusive_OR_expression_1 64
#define indx_logical_AND_expression_0 65
#define indx_logical_AND_expression_1 66
#define indx_logical_OR_expression_0 67
#define indx_logical_OR_expression_1 68
#define indx_conditional_expression_0 69
#define indx_conditional_expression_1 70
#define indx_assignment_expression_0 71
#define indx_assignment_expression_1 72
#define indx_assignment_operator_0 73
#define indx_assignment_operator_1 74
#define indx_assignment_operator_2 75
#define indx_assignment_operator_3 76
#define indx_assignment_operator_4 77
#define indx_assignment_operator_5 78
#define indx_assignment_operator_6 79
#define indx_assignment_operator_7 80
#define indx_assignment_operator_8 81
#define indx_assignment_operator_9 82
#define indx_assignment_operator_10 83
#define indx_expression_0 84
#define indx_expression_1 85
#define indx_constant_expression_0 86
#define indx_declaration_0 87
#define indx_declaration_1 88
#define indx_declaration_specifiers_0 89
#define indx_declaration_specifiers_1 90
#define indx_declaration_specifiers_2 91
#define indx_declaration_specifiers_3 92
#define indx_declaration_specifiers_4 93
#define indx_declaration_specifiers_5 94
#define indx_declaration_specifiers_6 95
#define indx_declaration_specifiers_7 96
#define indx_init_declarator_list_0 97
#define indx_init_declarator_list_1 98
#define indx_init_declarator_0 99
#define indx_init_declarator_1 100
#define indx_storage_class_specifier_0 101
#define indx_storage_class_specifier_1 102
#define indx_storage_class_specifier_2 103
#define indx_storage_class_specifier_3 104
#define indx_storage_class_specifier_4 105
#define indx_type_specifier_0 106
#define indx_type_specifier_1 107
#define indx_type_specifier_2 108
#define indx_type_specifier_3 109
#define indx_type_specifier_4 110
#define indx_type_specifier_5 111
#define indx_type_specifier_6 112
#define indx_type_specifier_7 113
#define indx_type_specifier_8 114
#define indx_type_specifier_9 115
#define indx_struct_or_union_specifier_0 116
#define indx_struct_or_union_specifier_1 117
#define indx_struct_or_union_specifier_2 118
#define indx_struct_or_union_0 119
#define indx_struct_or_union_1 120
#define indx_struct_declaration_list_0 121
#define indx_struct_declaration_list_1 122
#define indx_struct_declaration_0 123
#define indx_struct_declaration_1 124
#define indx_specifier_qualifier_list_0 125
#define indx_specifier_qualifier_list_1 126
#define indx_specifier_qualifier_list_2 127
#define indx_specifier_qualifier_list_3 128
#define indx_struct_declarator_list_0 129
#define indx_struct_declarator_list_1 130
#define indx_struct_declarator_0 131
#define indx_struct_declarator_1 132
#define indx_struct_declarator_2 133
#define indx_enum_specifier_0 134
#define indx_enum_specifier_1 135
#define indx_enum_specifier_2 136
#define indx_enum_specifier_3 137
#define indx_enum_specifier_4 138
#define indx_emumerator_list_0 139
#define indx_emumerator_list_1 140
#define indx_emumerator_0 141
#define indx_emumerator_1 142
#define indx_type_qualifier_0 143
#define indx_type_qualifier_1 144
#define indx_attribute_param_list_0 145
#define indx_attribute_param_list_1 146
#define indx_attribute_list_0 147
#define indx_attribute_list_1 148
#define indx_attribute_list_2 149
#define indx_function_speficier_0 150
#define indx_function_speficier_1 151
#define indx_declarator_0 152
#define indx_declarator_1 153
#define indx_direct_declarator_0 154
#define indx_direct_declarator_1 155
#define indx_direct_declarator_2 156
#define indx_direct_declarator_3 157
#define indx_direct_declarator_4 158
#define indx_direct_declarator_5 159
#define indx_direct_declarator_6 160
#define indx_direct_declarator_7 161
#define indx_direct_declarator_8 162
#define indx_direct_declarator_9 163
#define indx_direct_declarator_10 164
#define indx_direct_declarator_11 165
#define indx_direct_declarator_12 166
#define indx_direct_declarator_13 167
#define indx_pointer_0 168
#define indx_pointer_1 169
#define indx_pointer_2 170
#define indx_pointer_3 171
#define indx_type_qualifier_list_0 172
#define indx_type_qualifier_list_1 173
#define indx_parameter_type_list_0 174
#define indx_parameter_type_list_1 175
#define indx_parameter_list_0 176
#define indx_parameter_list_1 177
#define indx_parameter_declaration_0 178
#define indx_parameter_declaration_1 179
#define indx_parameter_declaration_2 180
#define indx_identifier_list_0 181
#define indx_identifier_list_1 182
#define indx_type_name_0 183
#define indx_type_name_1 184
#define indx_abstract_declarator_0 185
#define indx_abstract_declarator_1 186
#define indx_abstract_declarator_2 187
#define indx_direct_abstract_declarator_0 188
#define indx_direct_abstract_declarator_1 189
#define indx_direct_abstract_declarator_2 190
#define indx_direct_abstract_declarator_3 191
#define indx_direct_abstract_declarator_4 192
#define indx_direct_abstract_declarator_5 193
#define indx_direct_abstract_declarator_6 194
#define indx_direct_abstract_declarator_7 195
#define indx_direct_abstract_declarator_8 196
#define indx_direct_abstract_declarator_9 197
#define indx_direct_abstract_declarator_10 198
#define indx_direct_abstract_declarator_11 199
#define indx_direct_abstract_declarator_12 200
#define indx_direct_abstract_declarator_13 201
#define indx_direct_abstract_declarator_14 202
#define indx_direct_abstract_declarator_15 203
#define indx_direct_abstract_declarator_16 204
#define indx_direct_abstract_declarator_17 205
#define indx_direct_abstract_declarator_18 206
#define indx_direct_abstract_declarator_19 207
#define indx_direct_abstract_declarator_20 208
#define indx_typedef_name_0 209
#define indx_initializer_0 210
#define indx_initializer_1 211
#define indx_initializer_2 212
#define indx_initializer_list_0 213
#define indx_initializer_list_1 214
#define indx_initializer_list_2 215
#define indx_initializer_list_3 216
#define indx_designation_0 217
#define indx_designator_list_0 218
#define indx_designator_list_1 219
#define indx_designator_0 220
#define indx_designator_1 221
#define indx_statement_0 222
#define indx_statement_1 223
#define indx_statement_2 224
#define indx_statement_3 225
#define indx_statement_4 226
#define indx_statement_5 227
#define indx_labeled_statement_0 228
#define indx_labeled_statement_1 229
#define indx_labeled_statement_2 230
#define indx_compound_statement_0 231
#define indx_compound_statement_1 232
#define indx_block_item_list_0 233
#define indx_block_item_list_1 234
#define indx_block_item_0 235
#define indx_block_item_1 236
#define indx_expression_statement_0 237
#define indx_expression_statement_1 238
#define indx_selection_statement_0 239
#define indx_selection_statement_1 240
#define indx_selection_statement_2 241
#define indx_iteration_statement_0 242
#define indx_iteration_statement_1 243
#define indx_iteration_statement_2 244
#define indx_iteration_statement_3 245
#define indx_iteration_statement_4 246
#define indx_iteration_statement_5 247
#define indx_iteration_statement_6 248
#define indx_iteration_statement_7 249
#define indx_iteration_statement_8 250
#define indx_iteration_statement_9 251
#define indx_iteration_statement_10 252
#define indx_iteration_statement_11 253
#define indx_iteration_statement_12 254
#define indx_iteration_statement_13 255
#define indx_jump_statement_0 256
#define indx_jump_statement_1 257
#define indx_jump_statement_2 258
#define indx_jump_statement_3 259
#define indx_jump_statement_4 260
#define indx_translation_unit_0 261
#define indx_translation_unit_1 262
#define indx_external_declaration_0 263
#define indx_external_declaration_1 264
#define indx_function_definition_0 265
#define indx_function_definition_1 266
#define indx_declaration_list_0 267
#define indx_declaration_list_1 268

#define IDTBL_SIZE 269

#endif /*__idtbl_h__*/
